# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 01f79dde9016a26650751b17f857b4dc450fd58fff4f4782b7f61e02b6fdfe336b13bd9e7f4ac82f1f04fbb4f67eb2b1eababb5824d71066487667dd3250e256

test:
  secret_key_base: bc905b289540245ba2e1a92db801cbc738d07a5e066d68e398c3136b0d0065230b65fecf407704e6c28dc8581e3118274731972bf8af03b06897798ed1a1a61a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
